### PR TITLE
Fixed anonymous auth

### PR DESCRIPTION
**Pull request by lap1nou**
Hello,

Connection URL such as `rdp+ntlm-password://IP`, were working with version `0.0.8` of `aardwolf` but they aren't working now with the latest version.

I'm not sure but I think it's because the logic for anonymous authentication was not ported to this new `asysauth` library.

## Actual behaviour:
Using this URL connection `rdp+ntlm-password://IP` I receive:
```
File "/root/.cache/pypoetry/virtualenvs/crackmapexec-Lq1srH_V-py3.9/lib/python3.9/site-packages/asyauth/protocols/ntlm/creds_calc.py", line 523, in NTOWFv1
    return hashlib.md4(password.encode('utf-16le')).digest()
AttributeError: 'NoneType' object has no attribute 'encode'
```

because the `password` attribute is `None`, which is logic.

However if I'm using this URL connection `rdp+ntlm-password://:@IP`, both `username` and `password` are equal to '' (empty), I receive a `0xc000006d` code which I think means **the username or password is incorrect.**

## Wanted behaviour:
Using this URL connection `rdp+ntlm-password://IP` I want to authenticate as anonymous, like the previous version of `aardwolf`. 

Sorry in advance if it's a mistake from my side.

Regards.

### CODE REVIEW

**Comment by skelsec** [comment]
Hello,
Indeed that was working in the previous version, however that was a mistake on my part actually which has been corrected :)  
RDP protocol supports CredSSP or the "plain" auth method. When specifying a URL with NTLM or Kerberos auth methods, under the hood it actually uses CredSSP together with NTLM or Kerberos, because CredSSPI -similarly to SPNEGO- is just selecting either of those plus it adds channel binding.  
Anonymous RDP authentication can be done with the "plain" authentication method, because with CredSSP you MUST perform the authentication with a secret. If you don't have a secret (read password or similar) then CredSSP is not gonna work.  
Please try `rdp+simple-password://10.10.10.2` or `aardpclient 'rdp://10.10.10.2'`
